 <?php

use Illuminate\Database\Seeder;

class PoliticalPartiesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('political_parties')->delete();
        
        \DB::table('political_parties')->insert(array (
            0 => 
            array (
                'id' => '62',
                'user_id' => '1',
                'name' => 'Orange Democratic Movement',
                'abbreviation' => 'ODM',
                'status' => '0',
                'slogan' => '',
                'year_founded' => '',
                'logo' => '',
                'about' => '',
                'manifestos' => '',
                'deleted_at' => '2016-06-22 09:43:38',
                'created_at' => '2016-06-22 09:40:37',
                'updated_at' => '2016-06-22 09:43:38',
            ),
            1 => 
            array (
                'id' => '63',
                'user_id' => '1',
                'name' => 'Agano Party',
                'abbreviation' => 'AGANO',
                'status' => '0',
                'slogan' => '',
                'year_founded' => '',
                'logo' => '',
                'about' => '',
                'manifestos' => '',
                'deleted_at' => NULL,
                'created_at' => '2016-06-22 09:43:44',
                'updated_at' => '2016-06-22 09:43:44',
            ),
            2 => 
            array (
                'id' => '64',
                'user_id' => '1',
                'name' => 'Alliance Party of Kenya',
                'abbreviation' => 'APK',
                'status' => '0',
                'slogan' => '',
                'year_founded' => '',
                'logo' => '',
                'about' => '',
                'manifestos' => '',
                'deleted_at' => NULL,
                'created_at' => '2016-06-22 09:43:44',
                'updated_at' => '2016-06-22 09:43:44',
            ),
            3 => 
            array (
                'id' => '65',
                'user_id' => '1',
                'name' => 'Alliance of Real Change',
                'abbreviation' => 'ARK',
                'status' => '0',
                'slogan' => '',
                'year_founded' => '',
                'logo' => '',
                'about' => '',
                'manifestos' => '',
                'deleted_at' => NULL,
                'created_at' => '2016-06-22 09:43:44',
                'updated_at' => '2016-06-22 09:43:44',
            ),
            4 => 
            array (
                'id' => '66',
                'user_id' => '1',
                'name' => 'Chama Cha Mwananchi',
                'abbreviation' => 'CCM',
                'status' => '0',
                'slogan' => '',
                'year_founded' => '',
                'logo' => '',
                'about' => '',
                'manifestos' => '',
                'deleted_at' => NULL,
                'created_at' => '2016-06-22 09:43:44',
                'updated_at' => '2016-06-22 09:43:44',
            ),
            5 => 
            array (
                'id' => '67',
                'user_id' => '1',
                'name' => 'Chama Cha Uzalendo',
                'abbreviation' => 'CCUZ',
                'status' => '0',
                'slogan' => '',
                'year_founded' => '',
                'logo' => '',
                'about' => '',
                'manifestos' => '',
                'deleted_at' => NULL,
                'created_at' => '2016-06-22 09:43:44',
                'updated_at' => '2016-06-22 09:43:44',
            ),
            6 => 
            array (
                'id' => '68',
                'user_id' => '1',
                'name' => 'Conservative Party',
                'abbreviation' => 'CP',
                'status' => '0',
                'slogan' => '',
                'year_founded' => '',
                'logo' => '',
                'about' => '',
                'manifestos' => '',
                'deleted_at' => NULL,
                'created_at' => '2016-06-22 09:43:44',
                'updated_at' => '2016-06-22 09:43:44',
            ),
            7 => 
            array (
                'id' => '69',
                'user_id' => '1',
                'name' => 'Democratic Party of Kenya',
                'abbreviation' => 'DP',
                'status' => '0',
                'slogan' => '',
                'year_founded' => '',
                'logo' => '',
                'about' => '',
                'manifestos' => '',
                'deleted_at' => NULL,
                'created_at' => '2016-06-22 09:43:44',
                'updated_at' => '2016-06-22 09:43:44',
            ),
            8 => 
            array (
                'id' => '70',
                'user_id' => '1',
                'name' => 'Forum for the Restoration of Democracy-Asili',
                'abbreviation' => 'FORD-A',
                'status' => '0',
                'slogan' => '',
                'year_founded' => '',
                'logo' => '',
                'about' => '',
                'manifestos' => '',
                'deleted_at' => NULL,
                'created_at' => '2016-06-22 09:43:44',
                'updated_at' => '2016-06-22 09:43:44',
            ),
            9 => 
            array (
                'id' => '71',
                'user_id' => '1',
                'name' => 'Forum for the Restoration of Democracy-Kenya',
                'abbreviation' => 'FORD-K',
                'status' => '0',
                'slogan' => '',
                'year_founded' => '',
                'logo' => '',
                'about' => '',
                'manifestos' => '',
                'deleted_at' => NULL,
                'created_at' => '2016-06-22 09:43:44',
                'updated_at' => '2016-06-22 09:43:44',
            ),
            10 => 
            array (
                'id' => '72',
                'user_id' => '1',
                'name' => 'Forum for the Restoration of Democracy-People',
                'abbreviation' => 'FORD-P',
                'status' => '0',
                'slogan' => '',
                'year_founded' => '',
                'logo' => '',
                'about' => '',
                'manifestos' => '',
                'deleted_at' => NULL,
                'created_at' => '2016-06-22 09:43:44',
                'updated_at' => '2016-06-22 09:43:44',
            ),
            11 => 
            array (
                'id' => '73',
                'user_id' => '1',
                'name' => 'Farmers Party',
                'abbreviation' => 'FP',
                'status' => '0',
                'slogan' => '',
                'year_founded' => '',
                'logo' => '',
                'about' => '',
                'manifestos' => '',
                'deleted_at' => NULL,
                'created_at' => '2016-06-22 09:43:44',
                'updated_at' => '2016-06-22 09:43:44',
            ),
            12 => 
            array (
                'id' => '74',
                'user_id' => '1',
                'name' => 'Federal Party of Kenya',
                'abbreviation' => 'FPK',
                'status' => '0',
                'slogan' => '',
                'year_founded' => '',
                'logo' => '',
                'about' => '',
                'manifestos' => '',
                'deleted_at' => NULL,
                'created_at' => '2016-06-22 09:43:44',
                'updated_at' => '2016-06-22 09:43:44',
            ),
            13 => 
            array (
                'id' => '75',
                'user_id' => '1',
                'name' => 'Grand National Union',
                'abbreviation' => 'GNU',
                'status' => '0',
                'slogan' => '',
                'year_founded' => '',
                'logo' => '',
                'about' => '',
                'manifestos' => '',
                'deleted_at' => NULL,
                'created_at' => '2016-06-22 09:43:44',
                'updated_at' => '2016-06-22 09:43:44',
            ),
            14 => 
            array (
                'id' => '76',
                'user_id' => '1',
                'name' => 'Kenya African Democratic Union-Asili',
                'abbreviation' => 'KADU-A',
                'status' => '0',
                'slogan' => '',
                'year_founded' => '',
                'logo' => '',
                'about' => '',
                'manifestos' => '',
                'deleted_at' => NULL,
                'created_at' => '2016-06-22 09:43:45',
                'updated_at' => '2016-06-22 09:43:45',
            ),
            15 => 
            array (
                'id' => '77',
                'user_id' => '1',
                'name' => 'Kenya African National Union',
                'abbreviation' => 'KANU',
                'status' => '0',
                'slogan' => '',
                'year_founded' => '',
                'logo' => '',
                'about' => '',
                'manifestos' => '',
                'deleted_at' => NULL,
                'created_at' => '2016-06-22 09:43:45',
                'updated_at' => '2016-06-22 09:43:45',
            ),
            16 => 
            array (
                'id' => '78',
                'user_id' => '1',
                'name' => 'Kenya National Democratic Alliance',
                'abbreviation' => 'KENDA',
                'status' => '0',
                'slogan' => '',
                'year_founded' => '',
                'logo' => '',
                'about' => '',
                'manifestos' => '',
                'deleted_at' => NULL,
                'created_at' => '2016-06-22 09:43:45',
                'updated_at' => '2016-06-22 09:43:45',
            ),
            17 => 
            array (
                'id' => '79',
                'user_id' => '1',
                'name' => 'Kenya National Congress',
                'abbreviation' => 'KNC',
                'status' => '0',
                'slogan' => '',
                'year_founded' => '',
                'logo' => '',
                'about' => '',
                'manifestos' => '',
                'deleted_at' => NULL,
                'created_at' => '2016-06-22 09:43:45',
                'updated_at' => '2016-06-22 09:43:45',
            ),
            18 => 
            array (
                'id' => '80',
                'user_id' => '1',
                'name' => 'Kenya Social Congress',
                'abbreviation' => 'KSC',
                'status' => '0',
                'slogan' => '',
                'year_founded' => '',
                'logo' => '',
                'about' => '',
                'manifestos' => '',
                'deleted_at' => NULL,
                'created_at' => '2016-06-22 09:43:45',
                'updated_at' => '2016-06-22 09:43:45',
            ),
            19 => 
            array (
                'id' => '81',
                'user_id' => '1',
                'name' => 'Labour Party of Kenya',
                'abbreviation' => 'LPK',
                'status' => '0',
                'slogan' => '',
                'year_founded' => '',
                'logo' => '',
                'about' => '',
                'manifestos' => '',
                'deleted_at' => NULL,
                'created_at' => '2016-06-22 09:43:45',
                'updated_at' => '2016-06-22 09:43:45',
            ),
            20 => 
            array (
                'id' => '82',
                'user_id' => '1',
                'name' => 'Maendeleo Democratic Party',
                'abbreviation' => 'MDP',
                'status' => '0',
                'slogan' => '',
                'year_founded' => '',
                'logo' => '',
                'about' => '',
                'manifestos' => '',
                'deleted_at' => NULL,
                'created_at' => '2016-06-22 09:43:45',
                'updated_at' => '2016-06-22 09:43:45',
            ),
            21 => 
            array (
                'id' => '83',
                'user_id' => '1',
                'name' => 'Mazingira Greens Party of Kenya',
                'abbreviation' => 'MGPK',
                'status' => '0',
                'slogan' => '',
                'year_founded' => '',
                'logo' => '',
                'about' => '',
                'manifestos' => '',
                'deleted_at' => NULL,
                'created_at' => '2016-06-22 09:43:45',
                'updated_at' => '2016-06-22 09:43:45',
            ),
            22 => 
            array (
                'id' => '84',
                'user_id' => '1',
                'name' => 'Muungano Party',
                'abbreviation' => 'MP',
                'status' => '0',
                'slogan' => '',
                'year_founded' => '',
                'logo' => '',
                'about' => '',
                'manifestos' => '',
                'deleted_at' => NULL,
                'created_at' => '2016-06-22 09:43:45',
                'updated_at' => '2016-06-22 09:43:45',
            ),
            23 => 
            array (
                'id' => '85',
                'user_id' => '1',
                'name' => 'Mkenya Solidarity Movement',
                'abbreviation' => 'MSM',
                'status' => '0',
                'slogan' => '',
                'year_founded' => '',
                'logo' => '',
                'about' => '',
                'manifestos' => '',
                'deleted_at' => NULL,
                'created_at' => '2016-06-22 09:43:45',
                'updated_at' => '2016-06-22 09:43:45',
            ),
            24 => 
            array (
                'id' => '86',
                'user_id' => '1',
                'name' => 'Mzalendo Saba Saba Party',
                'abbreviation' => 'MSS',
                'status' => '0',
                'slogan' => '',
                'year_founded' => '',
                'logo' => '',
                'about' => '',
                'manifestos' => '',
                'deleted_at' => NULL,
                'created_at' => '2016-06-22 09:43:45',
                'updated_at' => '2016-06-22 09:43:45',
            ),
            25 => 
            array (
                'id' => '87',
                'user_id' => '1',
                'name' => 'Mwangaza Party',
                'abbreviation' => 'MWP',
                'status' => '0',
                'slogan' => '',
                'year_founded' => '',
                'logo' => '',
                'about' => '',
                'manifestos' => '',
                'deleted_at' => NULL,
                'created_at' => '2016-06-22 09:43:46',
                'updated_at' => '2016-06-22 09:43:46',
            ),
            26 => 
            array (
                'id' => '88',
                'user_id' => '1',
                'name' => 'National Agenda Party of Kenya',
                'abbreviation' => 'NAPK',
                'status' => '0',
                'slogan' => '',
                'year_founded' => '',
                'logo' => '',
                'about' => '',
                'manifestos' => '',
                'deleted_at' => NULL,
                'created_at' => '2016-06-22 09:43:46',
                'updated_at' => '2016-06-22 09:43:46',
            ),
            27 => 
            array (
                'id' => '89',
                'user_id' => '1',
                'name' => 'National Rainbow Coalition',
                'abbreviation' => 'NARC',
                'status' => '0',
                'slogan' => '',
                'year_founded' => '',
                'logo' => '',
                'about' => '',
                'manifestos' => '',
                'deleted_at' => NULL,
                'created_at' => '2016-06-22 09:43:46',
                'updated_at' => '2016-06-22 09:43:46',
            ),
            28 => 
            array (
                'id' => '90',
                'user_id' => '1',
                'name' => 'Narc-Kenya',
                'abbreviation' => 'NARC-K',
                'status' => '0',
                'slogan' => '',
                'year_founded' => '',
                'logo' => '',
                'about' => '',
                'manifestos' => '',
                'deleted_at' => NULL,
                'created_at' => '2016-06-22 09:43:46',
                'updated_at' => '2016-06-22 09:43:46',
            ),
            29 => 
            array (
                'id' => '91',
                'user_id' => '1',
                'name' => 'New Democrats',
                'abbreviation' => 'ND',
                'status' => '0',
                'slogan' => '',
                'year_founded' => '',
                'logo' => '',
                'about' => '',
                'manifestos' => '',
                'deleted_at' => NULL,
                'created_at' => '2016-06-22 09:43:46',
                'updated_at' => '2016-06-22 09:43:46',
            ),
            30 => 
            array (
                'id' => '92',
                'user_id' => '1',
                'name' => 'National Democratic Movement',
                'abbreviation' => 'NDM',
                'status' => '0',
                'slogan' => '',
                'year_founded' => '',
                'logo' => '',
                'about' => '',
                'manifestos' => '',
                'deleted_at' => NULL,
                'created_at' => '2016-06-22 09:43:46',
                'updated_at' => '2016-06-22 09:43:46',
            ),
            31 => 
            array (
                'id' => '93',
                'user_id' => '1',
                'name' => 'New Ford Kenya',
                'abbreviation' => 'NFK',
                'status' => '0',
                'slogan' => '',
                'year_founded' => '',
                'logo' => '',
                'about' => '',
                'manifestos' => '',
                'deleted_at' => NULL,
                'created_at' => '2016-06-22 09:43:46',
                'updated_at' => '2016-06-22 09:43:46',
            ),
            32 => 
            array (
                'id' => '94',
                'user_id' => '1',
                'name' => 'National Labour Party',
                'abbreviation' => 'NLP',
                'status' => '0',
                'slogan' => '',
                'year_founded' => '',
                'logo' => '',
                'about' => '',
                'manifestos' => '',
                'deleted_at' => NULL,
                'created_at' => '2016-06-22 09:43:46',
                'updated_at' => '2016-06-22 09:43:46',
            ),
            33 => 
            array (
                'id' => '95',
                'user_id' => '1',
                'name' => 'National Party of Kenya',
                'abbreviation' => 'NPK',
                'status' => '0',
                'slogan' => '',
                'year_founded' => '',
                'logo' => '',
                'about' => '',
                'manifestos' => '',
                'deleted_at' => NULL,
                'created_at' => '2016-06-22 09:43:46',
                'updated_at' => '2016-06-22 09:43:46',
            ),
            34 => 
            array (
                'id' => '96',
                'user_id' => '1',
                'name' => 'National Vision Party',
                'abbreviation' => 'NVP',
                'status' => '0',
                'slogan' => '',
                'year_founded' => '',
                'logo' => '',
                'about' => '',
                'manifestos' => '',
                'deleted_at' => NULL,
                'created_at' => '2016-06-22 09:43:46',
                'updated_at' => '2016-06-22 09:43:46',
            ),
            35 => 
            array (
                'id' => '97',
                'user_id' => '1',
                'name' => 'Orange Democratic Movement',
                'abbreviation' => 'ODM',
                'status' => '0',
                'slogan' => '',
                'year_founded' => '',
                'logo' => '',
                'about' => '',
                'manifestos' => '',
                'deleted_at' => NULL,
                'created_at' => '2016-06-22 09:43:46',
                'updated_at' => '2016-06-22 09:43:46',
            ),
            36 => 
            array (
                'id' => '98',
                'user_id' => '1',
                'name' => 'People\'s Democratic Party',
                'abbreviation' => 'PDP',
                'status' => '0',
                'slogan' => '',
                'year_founded' => '',
                'logo' => '',
                'about' => '',
                'manifestos' => '',
                'deleted_at' => NULL,
                'created_at' => '2016-06-22 09:43:46',
                'updated_at' => '2016-06-22 09:43:46',
            ),
            37 => 
            array (
                'id' => '99',
                'user_id' => '1',
                'name' => 'Party of Democratic Unity',
                'abbreviation' => 'PDU',
                'status' => '0',
                'slogan' => '',
                'year_founded' => '',
                'logo' => '',
                'about' => '',
                'manifestos' => '',
                'deleted_at' => NULL,
                'created_at' => '2016-06-22 09:43:46',
                'updated_at' => '2016-06-22 09:43:46',
            ),
            38 => 
            array (
                'id' => '100',
                'user_id' => '1',
                'name' => 'Progressive Party of Kenya',
                'abbreviation' => 'PGPK',
                'status' => '0',
                'slogan' => '',
                'year_founded' => '',
                'logo' => '',
                'about' => '',
                'manifestos' => '',
                'deleted_at' => NULL,
                'created_at' => '2016-06-22 09:43:46',
                'updated_at' => '2016-06-22 09:43:46',
            ),
            39 => 
            array (
                'id' => '101',
                'user_id' => '1',
                'name' => 'Party of Independent Candidates of Kenya',
                'abbreviation' => 'PICK',
                'status' => '0',
                'slogan' => '',
                'year_founded' => '',
                'logo' => '',
                'about' => '',
                'manifestos' => '',
                'deleted_at' => NULL,
                'created_at' => '2016-06-22 09:43:46',
                'updated_at' => '2016-06-22 09:43:46',
            ),
            40 => 
            array (
                'id' => '102',
                'user_id' => '1',
                'name' => 'Party of National Unity',
                'abbreviation' => 'PNU',
                'status' => '0',
                'slogan' => '',
                'year_founded' => '',
                'logo' => '',
                'about' => '',
                'manifestos' => '',
                'deleted_at' => NULL,
                'created_at' => '2016-06-22 09:43:46',
                'updated_at' => '2016-06-22 09:43:46',
            ),
            41 => 
            array (
                'id' => '103',
                'user_id' => '1',
                'name' => 'Party of Action',
                'abbreviation' => 'POA',
                'status' => '0',
                'slogan' => '',
                'year_founded' => '',
                'logo' => '',
                'about' => '',
                'manifestos' => '',
                'deleted_at' => NULL,
                'created_at' => '2016-06-22 09:43:46',
                'updated_at' => '2016-06-22 09:43:46',
            ),
            42 => 
            array (
                'id' => '104',
                'user_id' => '1',
                'name' => 'People\'s Party of Kenya',
                'abbreviation' => 'PPK',
                'status' => '0',
                'slogan' => '',
                'year_founded' => '',
                'logo' => '',
                'about' => '',
                'manifestos' => '',
                'deleted_at' => NULL,
                'created_at' => '2016-06-22 09:43:46',
                'updated_at' => '2016-06-22 09:43:46',
            ),
            43 => 
            array (
                'id' => '105',
                'user_id' => '1',
                'name' => 'People\'s Patriotic Party of Kenya',
                'abbreviation' => 'PPPK',
                'status' => '0',
                'slogan' => '',
                'year_founded' => '',
                'logo' => '',
                'about' => '',
                'manifestos' => '',
                'deleted_at' => NULL,
                'created_at' => '2016-06-22 09:43:46',
                'updated_at' => '2016-06-22 09:43:46',
            ),
            44 => 
            array (
                'id' => '106',
                'user_id' => '1',
                'name' => 'Restore and Build Kenya',
                'abbreviation' => 'RBK',
                'status' => '0',
                'slogan' => '',
                'year_founded' => '',
                'logo' => '',
                'about' => '',
                'manifestos' => '',
                'deleted_at' => NULL,
                'created_at' => '2016-06-22 09:43:46',
                'updated_at' => '2016-06-22 09:43:46',
            ),
            45 => 
            array (
                'id' => '107',
                'user_id' => '1',
                'name' => 'Republican Congress Party of Kenya',
                'abbreviation' => 'RC',
                'status' => '0',
                'slogan' => '',
                'year_founded' => '',
                'logo' => '',
                'about' => '',
                'manifestos' => '',
                'deleted_at' => NULL,
                'created_at' => '2016-06-22 09:43:46',
                'updated_at' => '2016-06-22 09:43:46',
            ),
            46 => 
            array (
                'id' => '108',
                'user_id' => '1',
                'name' => 'Republican Liberty Party',
                'abbreviation' => 'RLP',
                'status' => '0',
                'slogan' => '',
                'year_founded' => '',
                'logo' => '',
                'about' => '',
                'manifestos' => '',
                'deleted_at' => NULL,
                'created_at' => '2016-06-22 09:43:46',
                'updated_at' => '2016-06-22 09:43:46',
            ),
            47 => 
            array (
                'id' => '109',
                'user_id' => '1',
                'name' => 'Roots Party of Kenya',
                'abbreviation' => 'RPK',
                'status' => '0',
                'slogan' => '',
                'year_founded' => '',
                'logo' => '',
                'about' => '',
                'manifestos' => '',
                'deleted_at' => NULL,
                'created_at' => '2016-06-22 09:43:46',
                'updated_at' => '2016-06-22 09:43:46',
            ),
            48 => 
            array (
                'id' => '110',
                'user_id' => '1',
                'name' => 'Safina Party',
                'abbreviation' => 'SAFINA',
                'status' => '0',
                'slogan' => '',
                'year_founded' => '',
                'logo' => '',
                'about' => '',
                'manifestos' => '',
                'deleted_at' => NULL,
                'created_at' => '2016-06-22 09:43:46',
                'updated_at' => '2016-06-22 09:43:46',
            ),
            49 => 
            array (
                'id' => '111',
                'user_id' => '1',
                'name' => 'Social Democratic Party of Kenya',
                'abbreviation' => 'SDP',
                'status' => '0',
                'slogan' => '',
                'year_founded' => '',
                'logo' => '',
                'about' => '',
                'manifestos' => '',
                'deleted_at' => NULL,
                'created_at' => '2016-06-22 09:43:46',
                'updated_at' => '2016-06-22 09:43:46',
            ),
            50 => 
            array (
                'id' => '112',
                'user_id' => '1',
                'name' => 'Sisi Kwa Sisi Party of Kenya',
                'abbreviation' => 'SKSP',
                'status' => '0',
                'slogan' => '',
                'year_founded' => '',
                'logo' => '',
                'about' => '',
                'manifestos' => '',
                'deleted_at' => NULL,
                'created_at' => '2016-06-22 09:43:46',
                'updated_at' => '2016-06-22 09:43:46',
            ),
            51 => 
            array (
                'id' => '113',
                'user_id' => '1',
                'name' => 'Shirikisho Party of Kenya',
                'abbreviation' => 'SPK',
                'status' => '0',
                'slogan' => '',
                'year_founded' => '',
                'logo' => '',
                'about' => '',
                'manifestos' => '',
                'deleted_at' => NULL,
                'created_at' => '2016-06-22 09:43:47',
                'updated_at' => '2016-06-22 09:43:47',
            ),
            52 => 
            array (
                'id' => '114',
                'user_id' => '1',
                'name' => 'Saba Saba Asili Party',
                'abbreviation' => 'SSAP',
                'status' => '0',
                'slogan' => '',
                'year_founded' => '',
                'logo' => '',
                'about' => '',
                'manifestos' => '',
                'deleted_at' => NULL,
                'created_at' => '2016-06-22 09:43:47',
                'updated_at' => '2016-06-22 09:43:47',
            ),
            53 => 
            array (
                'id' => '115',
                'user_id' => '1',
                'name' => 'The Independent Party',
                'abbreviation' => 'TIP',
                'status' => '0',
                'slogan' => '',
                'year_founded' => '',
                'logo' => '',
                'about' => '',
                'manifestos' => '',
                'deleted_at' => NULL,
                'created_at' => '2016-06-22 09:43:47',
                'updated_at' => '2016-06-22 09:43:47',
            ),
            54 => 
            array (
                'id' => '116',
                'user_id' => '1',
                'name' => 'The National Alliance',
                'abbreviation' => 'TNA',
                'status' => '0',
                'slogan' => '',
                'year_founded' => '',
                'logo' => '',
                'about' => '',
                'manifestos' => '',
                'deleted_at' => NULL,
                'created_at' => '2016-06-22 09:43:47',
                'updated_at' => '2016-06-22 09:43:47',
            ),
            55 => 
            array (
                'id' => '117',
                'user_id' => '1',
                'name' => 'United Democratic Forum Party',
                'abbreviation' => 'UDF',
                'status' => '0',
                'slogan' => '',
                'year_founded' => '',
                'logo' => '',
                'about' => '',
                'manifestos' => '',
                'deleted_at' => NULL,
                'created_at' => '2016-06-22 09:43:47',
                'updated_at' => '2016-06-22 09:43:47',
            ),
            56 => 
            array (
                'id' => '118',
                'user_id' => '1',
                'name' => 'United Democratic Movement',
                'abbreviation' => 'UDM',
                'status' => '0',
                'slogan' => '',
                'year_founded' => '',
                'logo' => '',
                'about' => '',
                'manifestos' => '',
                'deleted_at' => NULL,
                'created_at' => '2016-06-22 09:43:47',
                'updated_at' => '2016-06-22 09:43:47',
            ),
            57 => 
            array (
                'id' => '119',
                'user_id' => '1',
                'name' => 'Unity Party of Kenya',
                'abbreviation' => 'UPK',
                'status' => '0',
                'slogan' => '',
                'year_founded' => '',
                'logo' => '',
                'about' => '',
                'manifestos' => '',
                'deleted_at' => NULL,
                'created_at' => '2016-06-22 09:43:47',
                'updated_at' => '2016-06-22 09:43:47',
            ),
            58 => 
            array (
                'id' => '120',
                'user_id' => '1',
                'name' => 'United Republican Party',
                'abbreviation' => 'URP',
                'status' => '0',
                'slogan' => '',
                'year_founded' => '',
                'logo' => '',
                'about' => '',
                'manifestos' => '',
                'deleted_at' => NULL,
                'created_at' => '2016-06-22 09:43:47',
                'updated_at' => '2016-06-22 09:43:47',
            ),
            59 => 
            array (
                'id' => '121',
                'user_id' => '1',
                'name' => 'Wiper Democrartic Movement-Kenya',
                'abbreviation' => 'WDM-K',
                'status' => '0',
                'slogan' => '',
                'year_founded' => '',
                'logo' => '',
                'about' => '',
                'manifestos' => '',
                'deleted_at' => NULL,
                'created_at' => '2016-06-22 09:43:47',
                'updated_at' => '2016-06-22 09:43:47',
            ),
        ));
        
        
    }
}
